name: Lint

on: pull_request

jobs:
  eslint:
    name: ESLintCheck
      # runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
          with:
            fetch-depth: 1
        - uses: tinovyatkin/action-eslint@v1
          with:
            repo-token: ${{secrets.GITHUB_TOKEN}}
            check-name: eslint