name: CI

on: [push]
resolves: ["ESLint"]
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install ESLint
      uses: hallee/eslint-action@master
