name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install ESLint
      run: npm i -g eslint
    - name: Run ESLint
      run: eslint index.js
