name: CI

on: [push]
resolves: ["ESLint"]
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install ESLint
      uses: hallee/eslint-action@master
      secrets: [a65a8d478327010084a15b647f3dca9f26368054]
